name: Test, build and coverage
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ReactRustTodo/backend
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --workspace --all-features
      - run: cargo build --workspace --all-features --release
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ReactRustTodo/backend
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with: { components: llvm-tools-preview }
      - run: cargo install cargo-llvm-cov
      - run: cargo llvm-cov --workspace --all-features --ignore-filename-regex '(.cargo/|tests/|examples/|target/|build.rs|main.rs|todo.rs|mysql_repo.rs|schema.rs)' --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }} # Token reference added here

